[package]
name = "sark_pathfinding"
version = "0.3.0"
edition = "2021"
homepage = "https://github.com/sarkahn/sark_pathfinding_rs"
repository = "https://github.com/sarkahn/sark_pathfinding_rs"
license = "MIT"
readme = "README.md"
description = "A simple implementation of the astar pathfinding algorthim from red blob games https://www.redblobgames.com/pathfinding/a-star/implementation.html."
keywords = ["bevy", "pathfinding", "2d", "astar"]

[dependencies]
glam = { version = "0.22" }
smallvec = "1.7.0"
ahash = "0.7.6"
arrayvec = "0.7.2"
sark_grids = {git = "https://github.com/sarkahn/sark_grids_rs.git", version = "0.5.5"}


[dev-dependencies]
bevy = {path="../bevy", version = "0.9", default-features = false, features = ["png", "bevy_winit", "render"]}
bevy_ascii_terminal = {path="../bevy_ascii_terminal", version="0.12" }
noise = "0.7.0"

[features]
dev = [
    "bevy/dynamic",
]
